architecture-beta
    group sys(cloud)[API]

    service dbSQL(database)[SQLMI] in sys
    service dbNoSQL(database)[MongoDB] in sys
    service disk1(disk)[Bob] in sys
    service serverv1(server)[V1] in sys
    service apiv3(server)[V3] in sys
    service serverrsp(server)[RSP] in sys
    service ui(server)[FrontEnd] in sys
    service serverruleengine(server)[RuleEngine] in sys

    ui:R -- L:apiv3
