architecture-beta
    group sys(cloud)[API]

    service db(database)[SQLMI] in sys
    service db(database)[MongoDB] in sys
    service disk1(disk)[Bob] in sys
    service server(server)[V1] in sys
    service server(server)[V3] in sys
    service server(server)[RSP] in sys
    service server(server)[RuleEngine] in sys

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
