database:
  type: postgresql  # or mysql, sqlite, etc.
  host: localhost
  port: 5432
  database: your_database
  user: your_user
  password: your_password

queries:
  - name: users_report
    sql: |
      SELECT 
        id,
        username,
        email,
        created_at
      FROM users
      WHERE created_at >= :start_date
    output:
      format: csv
      file: output/users_report.csv
      encoding: utf-8
      include_headers: true
    parameters:
      start_date: "2024-01-01"

  - name: orders_summary
    sql: |
      SELECT 
        DATE_TRUNC('month', order_date) as month,
        COUNT(*) as total_orders,
        SUM(amount) as total_amount
      FROM orders
      GROUP BY DATE_TRUNC('month', order_date)
      ORDER BY month
    output:
      format: excel
      file: output/orders_summary.xlsx
      sheet_name: Monthly Summary 